#  This file contains properties meant to be used in QAS Environment

http:
  protocol: "HTTP"
  port: "80"
    
api:
  id: "9999999"
 
# Example Connection
#example:
#  host: "example.us-e2.cloudhub.io"
#  port: "80"
#  protocol: "HTTP"
#  path: "/api/"
#  timeout: "400000"